services:
  postgres:
    image: postgres:15-alpine
    container_name: employee_db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fresh7182
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cmd/migrate/migrations/000001_create_employee_table_up.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - employee_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: fresh7182
      DB_NAME: employee_db
      DB_SSLMODE: disable
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - employee_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  employee_network:
    driver: bridge